### ISSUE TITLE
Move `monitor.go` into a package?

### ISSUE THREAD

**Issue by terencechain** [ralexstokes/relay-monitor#13]
Currently `monitor.go` is in an odd spot. Perhaps we should create a new folder `monitor` and move it under there
```
.
├── api
│   └── server.go
├── builder
│   ├── client.go
│   └── client_test.go
├── consensus
│   ├── client.go
│   └── clock.go
├── monitor.go
└── types
    └── types.go
```

👇🏼 

```
├── api
│   └── server.go
├── builder
│   ├── client.go
│   └── client_test.go
├── consensus
│   ├── client.go
│   └── clock.go
├── monitor
│   └── service.go
└── types
    └── types.go
```

**Comment by CypherpunkSamurai** [comment]
Hello Sir, I'm new to open-source, would you mind if I takeover this issue?

I can move the `monitor.go` to a new package and refactor the project :)

**Comment by terencechain** [comment]
> Hello Sir, I'm new to open-source, would you mind if I takeover this issue?
> 
> I can move the `monitor.go` to a new package and refactor the project :)

Sounds good. Thanks!

**Comment by CypherpunkSamurai** [comment]
Hello Sir, 

I've created a draft commit https://github.com/CypherpunkSamurai/relay-monitor/commit/93744b1b171ca59fb3b342db9a1a32b99ee03c16. Please review changes :

**Comment by ralexstokes** [comment]
sorry to move ahead of this issue, but I have refactored some of the code in #22 and this is no longer relevant
