### ISSUE TITLE
Add CI/linting

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/relay-monitor#2]
copy parts of this?

https://github.com/flashbots/go-template

**Comment by metachris** [comment]
I'd recommend to base test & linting on https://github.com/flashbots/mev-boost-relay/blob/main/.github/workflows/checks.yml where Justin T. has put in a lot of effort already. Guides for local setup are in https://github.com/flashbots/mev-boost-relay/blob/main/CONTRIBUTING.md and there's also `make lint`: https://github.com/flashbots/mev-boost-relay/blob/main/Makefile#L20-L25
